
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andra Maret
 */
public class Frame1 extends javax.swing.JFrame {
    String temp="";
    Double ti, bt, h1;
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        berat1 = new javax.swing.JTextField();
        kideal = new javax.swing.JTextField();
        tinggi1 = new javax.swing.JTextField();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        saran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 330, 170, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 30, 140, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("cm");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 120, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 120, 40, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Berat Badan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 160, 80, 20);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 240, 80, 30);

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 240, 80, 30);

        jButton3.setText("Coba Lagi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 240, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 200, 90, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 290, 200, 20);
        getContentPane().add(berat1);
        berat1.setBounds(160, 160, 50, 30);
        getContentPane().add(kideal);
        kideal.setBounds(260, 290, 90, 30);
        getContentPane().add(tinggi1);
        tinggi1.setBounds(160, 120, 50, 30);

        buttonGroup1.add(rb1);
        rb1.setText("Perempuan");
        getContentPane().add(rb1);
        rb1.setBounds(170, 200, 100, 23);

        buttonGroup1.add(rb2);
        rb2.setText("Laki - laki");
        getContentPane().add(rb2);
        rb2.setBounds(280, 200, 90, 23);
        getContentPane().add(saran);
        saran.setBounds(60, 400, 330, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nama");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 80, 40, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 290, 40, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 160, 40, 20);
        getContentPane().add(nama1);
        nama1.setBounds(160, 80, 230, 30);
        getContentPane().add(hasil);
        hasil.setBounds(60, 360, 330, 30);

        setBounds(0, 0, 436, 514);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(nama1.getText().equals("")||tinggi1.getText().equals("")||
                berat1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data inputan harus diisi");
        }else if(rb1.isSelected()||rb2.isSelected()){
            try{
                Proses();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data inputan salah");
            }
        } else{
           JOptionPane.showMessageDialog(null, "Jenis Kelamin belum dipilih"); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        nama1.setText("");
        tinggi1.setText("");
        berat1.setText("");
        kideal.setText("");
        hasil.setText("");
        saran.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kideal;
    private javax.swing.JTextField nama1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi1;
    // End of variables declaration//GEN-END:variables
private void Proses() {
       ti = Double.valueOf(tinggi1.getText());
       bt = Double.valueOf(berat1.getText());
       
       if(rb1.isSelected()){
           h1 = (ti - 110) * 1;
       } else if(rb2.isSelected()){
           h1 = (ti -100) * 1;
       }
       temp = Double.toString(h1.intValue());
       
       if(h1<bt){
           kideal.setText(temp);
           hasil.setText("Maaf " + nama1.getText() + " , Sepertinya anda Overweight :(");
           saran.setText("Banyaklah berolahraga dan hindari makanan berkolestrol");
       } else if(h1>bt){
           kideal.setText(temp);
           hasil.setText("Maaf " + nama1.getText() + " , Sepertinya anda Underweight :(");
           saran.setText("Banyaklah mengkonsumsi makanan yang berkabohidrat");
       } else {
           kideal.setText(temp);
           hasil.setText("Hallo" + nama1.getText() + ", Berat badan anda sudah ideal^^");
           saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat^^");
       }
    }
}
